#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zip
Version  : 3.0
Release  : 27
URL      : https://sourceforge.net/projects/infozip/files/Zip%203.x%20%28latest%29/3.0/zip30.tar.gz
Source0  : https://sourceforge.net/projects/infozip/files/Zip%203.x%20%28latest%29/3.0/zip30.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: zip-bin = %{version}-%{release}
Requires: zip-license = %{version}-%{release}
Requires: zip-man = %{version}-%{release}
BuildRequires : bzip2-dev
Patch1: cflags.patch
Patch2: format.patch
Patch3: manpages.patch

%description
Zip 3.0 is the first Zip update adding large file support.  For now Zip 2.3x
remains available and supported, but users should switch to this new release.

%package bin
Summary: bin components for the zip package.
Group: Binaries
Requires: zip-license = %{version}-%{release}

%description bin
bin components for the zip package.


%package license
Summary: license components for the zip package.
Group: Default

%description license
license components for the zip package.


%package man
Summary: man components for the zip package.
Group: Default

%description man
man components for the zip package.


%prep
%setup -q -n zip30
cd %{_builddir}/zip30
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1664893906
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags}  CFLAGS="$CFLAGS" BIND="gcc $LDFLAGS" -f unix/Makefile generic_gcc


%install
export SOURCE_DATE_EPOCH=1664893906
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/zip
cp %{_builddir}/zip30/LICENSE %{buildroot}/usr/share/package-licenses/zip/b440a2eeacdbd257d99f253ac9a2127bc421c736 || :
%makeinstall -f unix/Makefile

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/zip
/usr/bin/zipcloak
/usr/bin/zipnote
/usr/bin/zipsplit

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/zip/b440a2eeacdbd257d99f253ac9a2127bc421c736

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/zip.1
/usr/share/man/man1/zipcloak.1
/usr/share/man/man1/zipnote.1
/usr/share/man/man1/zipsplit.1
